
// 题库数据文件 (data.js)
// 这里存放所有的英文单字数据，按分类整理

const questionBank = [
    // 动物/昆虫
    { word: "animal", meaning: "動物", category: "animal" },
    { word: "bear", meaning: "熊", category: "animal" },
    { word: "bee", meaning: "蜜蜂", category: "animal" },
    { word: "bird", meaning: "鳥", category: "animal" },
    { word: "bite", meaning: "咬", category: "animal" },
    { word: "butterfly", meaning: "蝴蝶", category: "animal" },
    { word: "cat", meaning: "貓", category: "animal" },
    { word: "chicken", meaning: "雞", category: "animal" },
    { word: "cow", meaning: "乳牛", category: "animal" },
    { word: "dog", meaning: "狗", category: "animal" },
    { word: "duck", meaning: "鴨子", category: "animal" },
    { word: "elephant", meaning: "大象", category: "animal" },
    { word: "fish", meaning: "魚", category: "animal" },
    { word: "frog", meaning: "青蛙", category: "animal" },
    { word: "hippo", meaning: "河馬", category: "animal" },
    { word: "horse", meaning: "馬", category: "animal" },
    { word: "koala", meaning: "無尾熊", category: "animal" },
    { word: "lion", meaning: "獅子", category: "animal" },
    { word: "mice", meaning: "老鼠（複數）", category: "animal" },
    { word: "monkey", meaning: "猴子", category: "animal" },
    { word: "mouse", meaning: "老鼠", category: "animal" },
    { word: "panda", meaning: "大貓熊", category: "animal" },
    { word: "pet", meaning: "寵物", category: "animal" },
    { word: "pig", meaning: "豬", category: "animal" },
    { word: "rabbit", meaning: "兔子", category: "animal" },
    { word: "sheep", meaning: "綿羊", category: "animal" },
    { word: "snake", meaning: "蛇", category: "animal" },
    { word: "spider", meaning: "蜘蛛", category: "animal" },
    { word: "tiger", meaning: "老虎", category: "animal" },
    { word: "whale", meaning: "鯨魚", category: "animal" },
    { word: "zebra", meaning: "斑馬", category: "animal" },

    // 衣服/配件
    { word: "bag", meaning: "包包", category: "clothes" },
    { word: "cap", meaning: "棒球帽", category: "clothes" },
    { word: "clothes", meaning: "衣服", category: "clothes" },
    { word: "coat", meaning: "外套", category: "clothes" },
    { word: "dress", meaning: "洋裝", category: "clothes" },
    { word: "glasses", meaning: "眼鏡", category: "clothes" },
    { word: "hat", meaning: "帽子", category: "clothes" },
    { word: "jacket", meaning: "夾克外套", category: "clothes" },
    { word: "pants", meaning: "長褲", category: "clothes" },
    { word: "pocket", meaning: "口袋", category: "clothes" },
    { word: "shirt", meaning: "襯衫", category: "clothes" },
    { word: "shoes", meaning: "鞋子", category: "clothes" },
    { word: "shorts", meaning: "短褲", category: "clothes" },
    { word: "skirt", meaning: "裙子", category: "clothes" },
    { word: "socks", meaning: "襪子", category: "clothes" },
    { word: "sweater", meaning: "毛衣", category: "clothes" },
    { word: "T-shirt", meaning: "T恤", category: "clothes" },
    { word: "umbrella", meaning: "傘", category: "clothes" },
    { word: "wear", meaning: "穿、戴", category: "clothes" },

    // 颜色
    { word: "black", meaning: "黑色的", category: "color" },
    { word: "blue", meaning: "藍色的", category: "color" },
    { word: "brown", meaning: "咖啡色", category: "color" },
    { word: "color", meaning: "顏色", category: "color" },
    { word: "gray", meaning: "灰色的", category: "color" },
    { word: "green", meaning: "綠色的", category: "color" },
    { word: "orange", meaning: "橘色的", category: "color" },
    { word: "pink", meaning: "粉紅色的", category: "color" },
    { word: "purple", meaning: "紫色的", category: "color" },
    { word: "red", meaning: "紅色的", category: "color" },
    { word: "white", meaning: "白色的", category: "color" },
    { word: "yellow", meaning: "黃色的", category: "color" },

    // 家庭
    { word: "aunt", meaning: "阿姨、姑姑", category: "family" },
    { word: "brother", meaning: "哥哥、弟弟", category: "family" },
    { word: "cousin", meaning: "堂兄弟姊妹", category: "family" },
    { word: "dad", meaning: "爸爸", category: "family" },
    { word: "daddy", meaning: "爸爸", category: "family" },
    { word: "daughter", meaning: "女兒", category: "family" },
    { word: "family", meaning: "家庭、家人", category: "family" },
    { word: "father", meaning: "爸爸", category: "family" },
    { word: "grandfather", meaning: "外公、爺爺", category: "family" },
    { word: "grandma", meaning: "外婆、奶奶", category: "family" },
    { word: "grandmother", meaning: "外婆、奶奶", category: "family" },
    { word: "grandpa", meaning: "外公、爺爺", category: "family" },
    { word: "mom", meaning: "媽媽", category: "family" },
    { word: "mommy", meaning: "媽媽", category: "family" },
    { word: "mother", meaning: "媽媽", category: "family" },
    { word: "parent", meaning: "父母親", category: "family" },
    { word: "sister", meaning: "姐姐、妹妹", category: "family" },
    { word: "son", meaning: "兒子", category: "family" },
    { word: "uncle", meaning: "叔叔、舅舅", category: "family" },

    // 食物/饮料
    { word: "apple", meaning: "蘋果", category: "food" },
    { word: "banana", meaning: "香蕉", category: "food" },
    { word: "beef", meaning: "牛肉", category: "food" },
    { word: "bread", meaning: "麵包", category: "food" },
    { word: "breakfast", meaning: "早餐", category: "food" },
    { word: "cake", meaning: "蛋糕", category: "food" },
    { word: "candy", meaning: "糖果", category: "food" },
    { word: "chicken", meaning: "雞肉", category: "food" },
    { word: "chocolate", meaning: "巧克力", category: "food" },
    { word: "coffee", meaning: "咖啡", category: "food" },
    { word: "cola", meaning: "可樂", category: "food" },
    { word: "coke", meaning: "可樂", category: "food" },
    { word: "cook", meaning: "做飯", category: "food" },
    { word: "cookies", meaning: "餅乾", category: "food" },
    { word: "dinner", meaning: "晚餐", category: "food" },
    { word: "drink", meaning: "喝", category: "food" },
    { word: "dumpling", meaning: "水餃", category: "food" },
    { word: "eat", meaning: "吃", category: "food" },
    { word: "egg", meaning: "蛋", category: "food" },
    { word: "fish", meaning: "魚肉", category: "food" },
    { word: "food", meaning: "食物", category: "food" },
    { word: "French fries", meaning: "薯條", category: "food" },
    { word: "fruit", meaning: "水果", category: "food" },
    { word: "full", meaning: "飽的", category: "food" },
    { word: "grape", meaning: "葡萄", category: "food" },
    { word: "hamburger", meaning: "漢堡", category: "food" },
    { word: "hungry", meaning: "餓的", category: "food" },
    { word: "ice cream", meaning: "冰淇淋", category: "food" },
    { word: "juice", meaning: "果汁", category: "food" },
    { word: "lemon", meaning: "檸檬", category: "food" },
    { word: "lunch", meaning: "午餐", category: "food" },
    { word: "meal", meaning: "餐", category: "food" },
    { word: "milk", meaning: "牛奶", category: "food" },
    { word: "noodles", meaning: "麵條", category: "food" },
    { word: "orange", meaning: "橘子", category: "food" },
    { word: "peach", meaning: "桃子", category: "food" },
    { word: "pie", meaning: "派", category: "food" },
    { word: "pizza", meaning: "披薩", category: "food" },
    { word: "pork", meaning: "豬肉", category: "food" },
    { word: "pumpkin", meaning: "南瓜", category: "food" },
    { word: "rice", meaning: "米飯", category: "food" },
    { word: "salad", meaning: "沙拉", category: "food" },
    { word: "sandwich", meaning: "三明治", category: "food" },
    { word: "soup", meaning: "湯", category: "food" },
    { word: "strawberry", meaning: "草莓", category: "food" },
    { word: "sweet", meaning: "甜的", category: "food" },
    { word: "taste", meaning: "嚐起來", category: "food" },
    { word: "tea", meaning: "茶", category: "food" },
    { word: "thirsty", meaning: "口渴的", category: "food" },
    { word: "water", meaning: "水", category: "food" },
    { word: "watermelon", meaning: "西瓜", category: "food" },
    { word: "yummy", meaning: "美味的", category: "food" },

    // 房子/居家
    { word: "bathroom", meaning: "浴室", category: "house" },
    { word: "bed", meaning: "床", category: "house" },
    { word: "bedroom", meaning: "臥房", category: "house" },
    { word: "chair", meaning: "椅子", category: "house" },
    { word: "clean", meaning: "乾淨的 / 清理", category: "house" },
    { word: "computer", meaning: "電腦", category: "house" },
    { word: "desk", meaning: "桌子", category: "house" },
    { word: "dining room", meaning: "餐廳（家裡）", category: "house" },
    { word: "door", meaning: "門", category: "house" },
    { word: "fan", meaning: "電扇", category: "house" },
    { word: "floor", meaning: "地板", category: "house" },
    { word: "fridge", meaning: "電冰箱", category: "house" },
    { word: "garden", meaning: "院子、花園", category: "house" },
    { word: "home", meaning: "家庭", category: "house" },
    { word: "house", meaning: "房子", category: "house" },
    { word: "key", meaning: "鑰匙", category: "house" },
    { word: "kitchen", meaning: "廚房", category: "house" },
    { word: "lamp", meaning: "燈", category: "house" },
    { word: "living room", meaning: "客廳", category: "house" },
    { word: "mop", meaning: "用拖把拖地", category: "house" },
    { word: "refrigerator", meaning: "電冰箱", category: "house" },
    { word: "shelf", meaning: "架子", category: "house" },
    { word: "shower", meaning: "淋浴", category: "house" },
    { word: "sofa", meaning: "沙發", category: "house" },
    { word: "street", meaning: "街道", category: "house" },
    { word: "sweep", meaning: "掃", category: "house" },
    { word: "table", meaning: "桌子", category: "house" },
    { word: "telephone", meaning: "電話", category: "house" },
    { word: "television", meaning: "電視", category: "house" },
    { word: "TV", meaning: "電視", category: "house" },
    { word: "towel", meaning: "毛巾", category: "house" },
    { word: "wall", meaning: "牆壁", category: "house" },
    { word: "wash", meaning: "洗", category: "house" },
    { word: "window", meaning: "窗戶", category: "house" },

    // 数字/金额
    { word: "all", meaning: "全部", category: "number" },
    { word: "both", meaning: "兩者都", category: "number" },
    { word: "eight", meaning: "八", category: "number" },
    { word: "eighteen", meaning: "十八", category: "number" },
    { word: "eighty", meaning: "八十", category: "number" },
    { word: "eleven", meaning: "十一", category: "number" },
    { word: "fifteen", meaning: "十五", category: "number" },
    { word: "fifty", meaning: "五十", category: "number" },
    { word: "first", meaning: "第一", category: "number" },
    { word: "five", meaning: "五", category: "number" },
    { word: "forty", meaning: "四十", category: "number" },
    { word: "four", meaning: "四", category: "number" }
];
